export enum Occurrence {
    HOURLY = 'HOURLY',
    DAILY = 'DAILY',
    MONTHLY = 'MONTHLY',
    YEARLY = 'YEARLY',
    ONCE = 'ONCE',
    WEEKLY = 'WEEKLY',
    BIWEEKLY = 'BIWEEKLY',
    SEMIMONTHLY = 'SEMIMONTHLY',
    BIYEARLY = 'BIYEARLY',
    QUARTERLY = 'QUARTERLY',
    ANNUALLY = 'ANNUALLY',
    SEMIANNUALLY = 'SEMIANNUALLY'
}